[general]
live_config_reload = true
import = [
  "./themes/themes/gruvbox_material_hard_dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.8

[mouse]
hide_when_typing = true

[window.padding]
x = 0
y = 0

[font]
size = 14

[font.bold]
family = "Iosevka Nerd Font"
style = "Heavy"

[font.bold_italic]
family = "Iosevka Nerd Font"
style = "Heavy Italic"

[font.italic]
family = "Iosevka Nerd Font"
style = "Medium Italic"

[font.normal]
family = "Iosevka Nerd Font"
style = "Medium"
